spring:
  application:
    name: kstream-merge-example

  kafka:
    streams:
      state-dir: ./target/kstream-statestore
      properties:
        default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler

logging:
  level:
    org.springframework.kafka: DEBUG
